import {
  Accessories,
  AccessoriesColor,
  ClotheGraphics,
  Clothes,
  ClothesColor,
  Eyebrow,
  Eyes,
  FacialHair,
  HairColor,
  HatColor,
  Mouth,
  Skin,
  Style,
  Top,
} from '@dicebear/avatars-avataaars-sprites/lib/options';

import {
  AvatarOptions,
  AvatarValues,
  CreateAvatarOption,
} from './avatar-generator.type';

export const style: Style[] = ['transparent', 'circle'];

export const hairColor: HairColor = [
  'auburn',
  'black',
  'blonde',
  'blondeGolden',
  'brown',
  'brownDark',
  'gray',
  'pastel',
  'pastelPink',
  'platinum',
  'red',
  'silverGray',
];

export const hatColor: HatColor = [
  'black',
  'blue',
  'blue01',
  'blue02',
  'blue03',
  'gray',
  'gray01',
  'gray02',
  'heather',
  'pastel',
  'pastelBlue',
  'pastelGreen',
  'pastelOrange',
  'pastelRed',
  'pastelYellow',
  'pink',
  'red',
  'white',
];

export const top: Top = [
  'longHair',
  'shortHair',
  'eyepatch',
  'hat',
  'hijab',
  'turban',
  'bigHair',
  'bob',
  'bun',
  'curly',
  'curvy',
  'dreads',
  'frida',
  'fro',
  'froAndBand',
  'miaWallace',
  'longButNotTooLong',
  'shavedSides',
  'straight01',
  'straight02',
  'straightAndStrand',
  'dreads01',
  'dreads02',
  'frizzle',
  'shaggy',
  'shaggyMullet',
  'shortCurly',
  'shortFlat',
  'shortRound',
  'shortWaved',
  'sides',
  'theCaesar',
  'theCaesarAndSidePart',
  'winterHat01',
  'winterHat02',
  'winterHat03',
  'winterHat04',
];

export const accessories: Accessories = [
  'kurt',
  'prescription01',
  'prescription02',
  'round',
  'sunglasses',
  'wayfarers',
];

export const accessoriesColor: AccessoriesColor = [
  'black',
  'blue',
  'blue01',
  'blue02',
  'blue03',
  'gray',
  'gray01',
  'gray02',
  'heather',
  'pastel',
  'pastelBlue',
  'pastelGreen',
  'pastelOrange',
  'pastelRed',
  'pastelYellow',
  'pink',
  'red',
  'white',
];

export const facialHair: FacialHair = [
  'medium',
  'beardMedium',
  'light',
  'beardLight',
  'majestic',
  'beardMajestic',
  'fancy',
  'moustaceFancy',
  'magnum',
  'moustacheMagnum',
];

export const clothes: Clothes = [
  'blazer',
  'blazerAndShirt',
  'blazerAndSweater',
  'sweater',
  'collarAndSweater',
  'shirt',
  'graphicShirt',
  'shirtCrewNeck',
  'shirtScoopNeck',
  'shirtVNeck',
  'hoodie',
  'overall',
];

export const clothesColor: ClothesColor = [
  'black',
  'blue',
  'blue01',
  'blue02',
  'blue03',
  'gray',
  'gray01',
  'gray02',
  'heather',
  'pastel',
  'pastelBlue',
  'pastelGreen',
  'pastelOrange',
  'pastelRed',
  'pastelYellow',
  'pink',
  'red',
  'white',
];

export const eyes: Eyes = [
  'close',
  'closed',
  'cry',
  'default',
  'dizzy',
  'xDizzy',
  'roll',
  'eyeRoll',
  'happy',
  'hearts',
  'side',
  'squint',
  'surprised',
  'wink',
  'winkWacky',
];

export const eyebrow: Eyebrow = [
  'angry',
  'angryNatural',
  'default',
  'defaultNatural',
  'flat',
  'flatNatural',
  'raised',
  'raisedExcited',
  'raisedExcitedNatural',
  'sad',
  'sadConcerned',
  'sadConcernedNatural',
  'unibrow',
  'unibrowNatural',
  'up',
  'upDown',
  'upDownNatural',
  'frown',
  'frownNatural',
];

export const mouth: Mouth = [
  'concerned',
  'default',
  'disbelief',
  'eating',
  'grimace',
  'sad',
  'scream',
  'screamOpen',
  'serious',
  'smile',
  'tongue',
  'twinkle',
  'vomit',
];

export const skin: Skin = [
  'tanned',
  'yellow',
  'pale',
  'light',
  'brown',
  'darkBrown',
  'black',
];

export const clotheGraphics: ClotheGraphics = [
  'skullOutline',
  'skull',
  'resist',
  'pizza',
  'hola',
  'diamond',
  'deer',
  'cumbia',
  'bear',
  'bat',
];

export const avatarOptions: AvatarOptions = {
  style,
  hairColor,
  hatColor,
  top,
  accessories,
  accessoriesColor,
  facialHair,
  clothes,
  clothesColor,
  eyes,
  eyebrow,
  mouth,
  skin,
  clotheGraphics,
};

export const avatarValues: AvatarValues = {
  style: 1,
  hairColor: 0,
  hatColor: 0,
  top: 27,
  accessories: 0,
  accessoriesColor: 0,
  facialHair: 0,
  clothes: 0,
  clothesColor: 0,
  eyes: 3,
  eyebrow: 3,
  mouth: 1,
  skin: 0,
  clotheGraphics: 0,
};

export function setCreateAvatarOption(
  avatarValues: AvatarValues
): CreateAvatarOption {
  return {
    style: avatarOptions.style[avatarValues.style],
    hairColor: [avatarOptions.hairColor[avatarValues.hairColor]],
    hatColor: [avatarOptions.hatColor[avatarValues.hatColor]],
    top: [avatarOptions.top[avatarValues.top]],
    accessories: [avatarOptions.accessories[avatarValues.accessories]],
    accessoriesColor: [
      avatarOptions.accessoriesColor[avatarValues.accessoriesColor],
    ],
    facialHair: [avatarOptions.facialHair[avatarValues.facialHair]],
    clothes: [avatarOptions.clothes[avatarValues.clothes]],
    clothesColor: [avatarOptions.clothesColor[avatarValues.clothesColor]],
    eyes: [avatarOptions.eyes[avatarValues.eyes]],
    eyebrow: [avatarOptions.eyebrow[avatarValues.eyebrow]],
    mouth: [avatarOptions.mouth[avatarValues.mouth]],
    skin: [avatarOptions.skin[avatarValues.skin]],
    clotheGraphics: [avatarOptions.clotheGraphics[avatarValues.clotheGraphics]],
  };
}
